backend/controllers/SettingController.php
<?php
/**
 * Created by PhpStorm.
 * User: akshay
 * Date: 10/5/17
 * Time: 11:30 PM
 */

namespace backend\controllers;
use backend\components\CustController;
use backend\models\Actions;
use backend\models\ActionSearch;
use backend\models\Controllers;
use backend\models\ControllerSearch;
use backend\models\ChangeUserPasswordForm;
use backend\models\Menus;
use backend\models\MenusSearch;
use backend\models\Rights;
use common\models\Role;
use common\models\form\SystemUserProfileForm;
use common\models\search\RoleSearch;
use common\models\search\UserSearch;
use common\models\AppUserProfile;

use kartik\form\ActiveForm;
use Yii;
use common\models\User;
use yii\web\Response;

/**
 * Setting controller
 */
class SettingController extends CustController
{

    /***
     * @Akshaysanagni
     *  List of User(System User)
     *  Who user Admin Panel
     **/
    public function actionIndex() {

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=PAGESIZE;
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /***
     * @AkshaySangani
     *  Add User(System User)
     *  Who user Admin Panel
     **/
    public function actionAddUser() {
        $model = new SystemUserProfileForm();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if (Yii::$app->request->post() && $model->load(Yii::$app->request->post())) {

            $transaction = Yii::$app->db->beginTransaction();
            $profile = new AppUserProfile();
            $profile->first_name = $model->first_name;
            $profile->last_name = $model->last_name;
            $profile->full_name = $model->first_name . " " . $model->last_name;
            $profile->email = $model->email;
            $profile->date_of_birth = $model->date_of_birth;
            $profile->phone_no = $model->phone_no;
            $profile->gender = $model->gender;
            $profile->is_deleted = NOT_DELETED;
            $profile->created_by = Yii::$app->user->identity->id;
            $profile->updated_by = Yii::$app->user->identity->id;
            $profile->is_app_user = 1;
            $profile->status = ACTIVE;
            $profile->created_date = time();
            $profile->updated_date = time();

            if($profile->validate()){
                $profile->save();

                $user = new User();
                $user->username = $model->email;
                $user->first_name = $model->first_name;
                $user->last_name = $model->last_name;
                $user->email = $model->email;
                $user->generateAuthKey();
                $user->setPassword(DEFAULT_PASSWORD);
                $user->profile_id = $profile->id;
                $user->password_reset_token = $user->generatePasswordResetToken();
                $user->role_id = $model->role;
                $user->screenlock = 0;
                $user->status = ACTIVE;
                $user->created_at = time();
                $user->updated_at = time();

                if ($user->validate()) {
                    $user->save();
                    $transaction->commit();
                    Yii::$app->getSession()->setFlash('success', [
                        'type' => 'success',
                        'duration' => 12000,
                        'icon' => 'glyphicon glyphicon-ok-sign',
                        'message' => 'You have created user & user successfully',
                        'title' => 'User Created',
                        'positonY' => 'top',
                        'positonX' => 'right'
                    ]);
                } else {
                    Yii::$app->getSession()->setFlash('danger', [
                        'type' => 'danger',
                        'duration' => 12000,
                        'icon' => 'glyphicon glyphicons-remove',
                        'message' => 'Something went wrong',
                        'title' => 'Error',
                        'positonY' => 'top',
                        'positonX' => 'right'
                    ]);
                    $transaction->rollBack();
                }
                return $this->redirect(Yii::$app->urlManager->createAbsoluteUrl('setting/index'));
            } else {
                Yii::$app->getSession()->setFlash('danger', [
                    'type' => 'danger',
                    'duration' => 12000,
                    'icon' => 'glyphicon glyphicons-remove',
                    'message' => 'Something went wrong',
                    'title' => 'Error',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
                $transaction->rollBack();
            }
        } else {
            return $this->render("add_system_user",[
                'model'=>$model
            ]);
        }
    }

    /***
     * @akshaysangani
     *  Edit User(System User)
     **/
    public function actionEditUser($id)
    {
        $model = new SystemUserProfileForm();
        $user = User::findIdentity($id);
        $model->first_name = $user->first_name;
        $model->last_name = $user->last_name;
        $model->email = $user->email;
        $model->phone_no = $user->profile->phone_no;
        $model->gender = $user->profile->gender;
        $model->date_of_birth = $user->profile->date_of_birth;
        $model->role = $user->role->id;

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if (Yii::$app->request->post() && $model->load(Yii::$app->request->post())) {

            $transaction = Yii::$app->db->beginTransaction();
            $profile = AppUserProfile::find()->where(['id' => $user->profile_id])->one();
            $profile->attributes = $model->attributes;
            $profile->full_name = $model->first_name . " " . $model->last_name;
            $profile->date_of_birth = $model->date_of_birth;
            $profile->updated_by = Yii::$app->user->identity->id;
            $profile->updated_date = time();

            if ($profile->validate()) {
                $profile->save(false);

                $user->attributes = $model->attributes;
                $user->role_id = $model->role;
                $user->updated_at = time();

                if ($user->validate()) {
                    $user->save(false);
                    $transaction->commit();
                    Yii::$app->getSession()->setFlash('success', [
                        'type' => 'success',
                        'duration' => 12000,
                        'icon' => 'glyphicon glyphicon-ok-sign',
                        'message' => 'User updated successfully',
                        'title' => 'User updated',
                        'positonY' => 'top',
                        'positonX' => 'right'
                    ]);

                    return $this->redirect(Yii::$app->urlManager->createAbsoluteUrl('setting/index'));
                } else {
                    $transaction->rollBack();
                    Yii::$app->getSession()->setFlash('danger', [
                        'type' => 'danger',
                        'duration' => 12000,
                        'icon' => 'glyphicon glyphicons-remove',
                        'message' => 'Something went wrong',
                        'title' => 'Error',
                        'positonY' => 'top',
                        'positonX' => 'right'
                    ]);
                    $transaction->rollBack();
                }

            } else {
                $transaction->rollBack();
                Yii::$app->getSession()->setFlash('danger', [
                    'type' => 'danger',
                    'duration' => 12000,
                    'icon' => 'glyphicon glyphicons-remove',
                    'message' => 'Something went wrong',
                    'title' => 'Error',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
                $transaction->rollBack();
            }
        }

        return $this->render("edit_system_user", [
            'model' => $model
        ]);
    }

    public function actionViewUser($id){
        return $this->render('view_user', [
            'model' => $this->findModel($id),
        ]);
    }

    protected function findModel($id){
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /***
     * @akshaysangani
     *  Change change Password of User(System User)
     *  Who user Admin Panel
     **/
    public function actionChangeUserPassword($id){
        $model = new ChangeUserPasswordForm();
        $model->user_id = $id;
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if(Yii::$app->request->post() && $model->load(Yii::$app->request->post())){
            $errors = ActiveForm::validate($model);
            if($errors){

            }else{
               // print_r($model->attributes);die;
                if($model->resetPassword()){
                    Yii::$app->getSession()->setFlash('success', [
                        'type' => 'success',
                        'duration' => 12000,
                        'icon' => 'glyphicon glyphicon-ok-sign',
                        'message' => 'You have changed user password successfully',

backend/views/setting/_form.php
<?php
/**
 * Created by PhpStorm.
 * User: akshay
 * Date: 10/5/17
 * Time: 11:30 PM
 */
use yii\bootstrap\ActiveForm;
use kartik\switchinput\SwitchInput;
use kartik\date\DatePicker;
use kartik\select2\Select2;
?>
<?php
$form = ActiveForm::begin([
    'id' => 'login-form',
    'options' => ['class' => 'form-horizontal form-label-left'],
]) ?>

<div class="form-group">
<label class="control-label col-md-3 col-sm-3 col-xs-12">Default Input</label>
    <div class="col-md-9 col-sm-9 col-xs-12">
<?= $form->field($model, 'username')->label(false) ?>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Default Input</label>
    <div class="col-md-9 col-sm-9 col-xs-12">
        <?= $form->field($model, 'status')->widget(SwitchInput::classname(), ['pluginOptions' => [
            'size' => 'small',
            'onColor' => 'success',
            'offColor' => 'danger',
            'onText' => '<i class="glyphicon glyphicon-ok"></i>',
            'offText' => '<i class="glyphicon glyphicon-remove"></i>',
        ]])->label(false);?>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Default Input</label>
    <div class="col-md-9 col-sm-9 col-xs-12">
        <?= $form->field($model, 'email')->passwordInput()->label(false) ?>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Default Input</label>
    <div class="checkbox">
        <label>
            <?= $form->field($model, 'status')->checkbox(["class"=>"flat"])->label(false) ?>
        </label>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Default Input</label>
    <div class="col-md-9 col-sm-9 col-xs-12">

            <?= $form->field($model, 'created_at')->widget(DatePicker::classname(), [
                'options' => ['placeholder' => 'Enter birth date ...'],
                'type' => DatePicker::TYPE_INPUT,
                'pluginOptions' => [
                   /* 'calendarWeeks' => true,*/
                    /*'daysOfWeekDisabled' => [0, 6],*/
                    'format' => 'dd-M-yyyy',
                    'autoclose' => true,
                ]
            ])->label(false);
            ?>
        </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12">Default Input</label>
    <div class="col-md-9 col-sm-9 col-xs-12">

        <?= $form->field($model, 'screenlock')->widget(Select2::classname(), [
            'data' => ["0"=>"admin","1"=>"superadmin"],
            'options' => ['placeholder' => 'Select a state ...'],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ])->label(false);
        ?>
    </div>
</div>

<?= \yii\bootstrap\Html::submitButton('Submit', ['class'=> 'btn btn-primary']) ;?>

<?php ActiveForm::end() ?>

backend/views/setting/_user_form.php
<?php
/**
 * Created by PhpStorm.
 * User: akshay
 * Date: 10/5/17
 * Time: 11:30 PM
 */

use yii\bootstrap\ActiveForm;
use kartik\switchinput\SwitchInput;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use common\models\Role;
use common\models\Media;
?>

<?php $form = ActiveForm::begin([
    'id' => 'client-form',
    'enableAjaxValidation' => true,
    'enableClientValidation'=>true,
]) ?>
<div class="row">
    <div class="col-md-6">
        <div class="form-group field-salonform-name required">
            <label class="control-label" for="salonform-name">First Name</label>
            <?= $form->field($model, 'first_name')->textInput(['placeholder'=>"i.e, John",'class'=>'form-control  required'])->label(false); ?>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group field-salonform-name required">
            <label class="control-label" for="salonform-name">Last Name</label>
            <?= $form->field($model, 'last_name')->textInput(['placeholder'=>"i.e, Doe",'class'=>'form-control  required'])->label(false); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group field-salonform-area required">
            <label class="control-label" for="salonform-area">Email</label>
            <?= $form->field($model, 'email')->textInput(['id'=>'user_email','placeholder'=>"i.e, john@comapany.com",'class'=>'form-control  required'])->label(false); ?>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group field-salonform-address required">
            <label class="control-label" for="salonform-address">Phone No</label>
            <?= $form->field($model, 'phone_no')->widget(\yii\widgets\MaskedInput::className(), [
                'mask' => '(999) 999-9999',
            ])->label(false); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="form-group field-salonform-address required">
            <label class="control-label" for="salonform-address">Gender</label>
            <?= $form->field($model, 'gender')->widget(Select2::classname(), [
                'data' =>[0=>'Not Specified',1=>'Male',2=>'Female'],
                'options' => ['placeholder' => 'Select Gender'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ])->label(false);?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group field-salonform-area required">
            <label class="control-label" for="salonform-area">Date Of Birth</label>
            <?= $form->field($model, 'date_of_birth')->widget(
                DatePicker::className(), [
                'options' => ['placeholder' => 'Select Birth date'],
                'removeButton' => false,
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'yyyy-mm-dd',
                ]
            ])->label(false);?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group field-salonform-address required">
            <label class="control-label" for="salonform-address">Roles</label>
            <?php echo $form->field($model, 'role')->widget(
                \kartik\select2\Select2::classname(), [
                'data' => \yii\helpers\ArrayHelper::map(Role::find()->where(['not in','id',[SUPER_ADMIN]])->asArray()->all(), 'id', 'role_name'),
                'options' => ['placeholder' => 'Select Role ...'],
            ])->label(false); ?>
        </div>
    </div>
</div>
<div class="form-group">
    <button type="submit" class="btn btn-primary pull-right">Save</button>
</div>
<?php ActiveForm::end() ?>

backend/views/setting/actions.php
<?php
/**
 * Created by PhpStorm.
 * User: rohan
 * Date: 2/7/16
 * Time: 5:18 PM
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
?>
<?php echo \Yii::$app->view->renderFile('@backend/views/layouts/message_panel.php');?>

    <div class="right_col" role="main" style="height: 100%;
    min-height: 928px;">
        <div class="">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Actions</h2>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="pull-left">
                        <a class="btn btn-app" href="<?= \yii\helpers\Url::toRoute('setting/add-action') ?>">
                            <i class="fa fa-ellipsis-v"></i> Add Action
                        </a>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-app" href="<?= \yii\helpers\Url::toRoute('setting/index') ?>">
                            <i class="fa fa-hand-o-left"></i> Back to Settings
                        </a>
                    </div>
                    <?php Pjax::begin(['id' => 'menus']) ?>
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'summary' => "",
                        'showOnEmpty'=>true,
                        //'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                            [
                                'attribute' => 'controller_name',
                                'format'=>'raw',
                                'value' => function ($model) {
                                    return $model->controller->controller_name;
                                },
                            ],
                            [
                                'attribute' => 'action_name',
                                'format'=>'raw',
                                'value' => function ($model) {
                                    return $model->slug;
                                },
                            ],
                            [
                                'attribute' => 'slug',
                                'format'=>'raw',
                                'value' => function ($model) {
                                    return $model->slug;
                                },
                            ],


                            //['class' => 'yii\grid\ActionColumn'],
                            [
                                'class' => 'yii\grid\ActionColumn',
                                'template' => '{update} {delete} ',
                                'buttons' => [

                                    'delete'=>function ($url,$model){
                                        return Html::a('<span class="glyphicon glyphicon-remove" style="color:#b30000"></span>', $url,
                                            [
                                                'class'          => 'ajaxdelete',
                                                'title' => Yii::t('app', 'Status'),
                                                'status-url'     => $url,
                                                'pjax-container' => 'menus',
                                                'data-pjax'=>'w0',
                                            ]);
                                    }

                                ],
                                'urlCreator' => function ($action, $model, $key, $index) {

                                    if ($action === 'update') {
                                        return \yii\helpers\Url::to(['setting/edit-action/'.$key]);
                                    }
                                    if($action === 'delete'){
                                        return \yii\helpers\Url::to(['setting/delete-action/'.$key]);
                                    }
                                }
                            ],
                        ],
                    ]); ?>
                    <?php Pjax::end() ?>

                </div>
            </div>
        </div>
    </div>
<?php
$this->registerJs("

$(document).on('ready pjax:success', function () {
    $('.ajaxdelete').on('click', function (e) {
        e.preventDefault();
        var Url     = $(this).attr('status-url');
        var pjaxContainer = $(this).attr('pjax-container');
        if (!confirm('Do you want to delete?')){
            return false;
        }
            $.ajax({
                    url:   Url,
                    type:  'post',
                    error: function (xhr, status, error) {
                        alert('There was an error with your request.'
                            + xhr.responseText);
                        }
                }).done(function (data) {
                  $.pjax.reload({container: '#' + $.trim(pjaxContainer)});
                });

    });
});
");
?>

backend/views/setting/index.php
<?php
/**
 * Created by PhpStorm.
 * User: rohan
 * Date: 17/6/16
 * Time: 1:04 AM
 */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
?>

    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <!-- start: list-group navi for large devices -->
                <div class="panel panel-default">
                    <div class="panel-heading">Manage <strong>Settings</strong></div>
                    <div class="list-group">
                        <a class="list-group-item active" href="<?= Yii::$app->urlManager->createAbsoluteUrl('setting/index') ?>"><i class="fa fa-users"></i><span> System User </span></a>
                        <a class="list-group-item" href="<?= Yii::$app->urlManager->createAbsoluteUrl('setting/roles') ?>"><i class="fa fa-user"></i><span> Roles </span></a>
                        <a class="list-group-item" href="<?= Yii::$app->urlManager->createAbsoluteUrl('setting/rights') ?>"><i class="fa fa-user"></i><span> Rights </span></a>
                    </div>
                </div>
                <!-- end: list-group navi for large devices -->
            </div>
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>Users</strong> List <!-- check if flash message exists -->
                    </div>
                    <div class="panel-body">
                        <div class="help-block">
                            Here you can manage Salons which is listed on Application.
                        </div>
                        <div class="table-responsive">
                            <div class="pull-right">
                                <a class="btn btn-primary" href="<?= Yii::$app->urlManager->createAbsoluteUrl('setting/add-user') ?>"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;&nbsp;Add new user</a>
                            </div>
                            <?php Pjax::begin(['id' => 'users']) ?>
                            <?= \yii\grid\GridView::widget([
                                'dataProvider' => $dataProvider,
                                'filterModel' => $searchModel,
                                'layout' => "{pager}\n{summary}\n{items}",
                                'columns' => [
                                    ['class' => 'yii\grid\SerialColumn'],
                                    'first_name',
                                    'first_name',
                                    'email',
                                    [
                                        'attribute' => 'role',
                                        'format'=>'raw',
                                        'filter'=>\yii\helpers\ArrayHelper::map(\common\models\Role::find()->asArray()->all(), 'id', 'role_name'),
                                        'value' => function ($model) {
                                            return $model->role->role_name;
                                        },
                                    ],
                                    [
                                        'attribute' => 'created_at',
                                        'format'=>'raw',
                                        'filter'=>false,
                                        'value' => function ($model) {
                                            return date('d-M-y',$model->created_at);
                                        },
                                    ],
                                    [
                                        'attribute' => 'status',
                                        'format'=>'raw',
                                        'value' => function ($model) {
                                            //return ($model->status)?"<span class='label label-success pull-right'>Active</span>":"InActive";
                                            return ($model->status)? Html::tag('span', 'Active', ['class' => ['label','label-success']]):Html::tag('span', 'InActive', ['class' => ['label','label-danger']]);
                                        },
                                    ],
                                    [
                                        'class' => 'yii\grid\ActionColumn',
                                        'template' => ' {view} {update} {status} ',
                                        'buttons' => [
                                            'status' => function ($url, $model) {
                                                if($model->role->id != SUPER_ADMIN){
                                                    if($model->status == ACTIVE){
                                                        return Html::a('<i class="fa fa-times"></i>', $url,
                                                            [
                                                                'class'          => 'ajaxStatus btn btn-danger btn-xs tt',
                                                                'title' => Yii::t('app', 'Status'),
                                                                'status-url'     => $url,
                                                                'pjax-container' => 'users',
                                                                'data-pjax'=>'w0',
                                                            ]);
                                                    }else{
                                                        return Html::a('<i class="fa fa-check"></i>', $url,
                                                            [
                                                                'class'          => 'ajaxStatus btn btn-success btn-xs tt',
                                                                'title' => Yii::t('app', 'Status'),
                                                                'data-pjax'=>'w0',
                                                                'status-url'     => $url,
                                                                'pjax-container' => 'users',
                                                            ]);
                                                    }
                                                }

                                            },
                                            'update' => function ($url, $model) {

                                                return Html::a('<i class="fa fa-pencil"></i>', $url,
                                                    [
                                                        'class'          => 'btn btn-primary btn-xs tt',
                                                        'title' => Yii::t('app', 'Update'),
                                                        'data-pjax'=>'w0',
                                                        'status-url'     => $url,
                                                        'pjax-container' => 'users',
                                                    ]);

                                            },
                                            'view' => function ($url, $model) {

                                                return Html::a('<i class="fa fa-eye"></i>', $url,
                                                    [
                                                        'class'          => 'activity-view-link btn btn-primary btn-xs tt',
                                                        'title' => Yii::t('app', 'View'),
                                                        'data-pjax'=>'w0',
                                                        'status-url'     => $url,
                                                        'pjax-container' => 'users',
                                                    ]);

                                            }
                                        ],
                                        'urlCreator' => function ($action, $model, $key, $index) {

                                            if ($action === 'update') {
                                                return \yii\helpers\Url::to(['setting/edit-user/'.$key]);
                                            }
                                            if ($action === 'view') {
                                                return \yii\helpers\Url::to(['setting/view-user/'.$key]);
                                            }
                                            if ($action === 'status') {
                                                return \yii\helpers\Url::to(['setting/status-user/'.$key]);
                                            }
                                        }
                                    ],
                                ],
                                'tableOptions' => ['class' => 'table table-hover'],
                            ]); ?>
                            <?php \yii\widgets\Pjax::end() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
$this->registerJs("
$(document).on('ready pjax:success', function () {
    $('.ajaxStatus').on('click', function (e) {
        e.preventDefault();
        var Url     = $(this).attr('status-url');
        var pjaxContainer = $(this).attr('pjax-container');
            $.ajax({
                    url:   Url,
                    type:  'post',
                    error: function (xhr, status, error) {
                        alert('There was an error with your request.'
                            + xhr.responseText);
                        }
                }).done(function (data) {
                  $.pjax.reload({container: '#' + $.trim(pjaxContainer)});
                });

    });
});

");
?>